baseURL = 'https://victorious-bay-042228303.3.azurestaticapps.net/'
languageCode = 'en-us'
title = 'Emre Apa'
theme = 'hermit-v2'

[author]
  name = "Emre Apa"
  about = "about"


[params]

  homeSubtitle = "A personal blog by Emre Apa"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 20


  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 10


[[params.social]]
  name = "github"
  url = "https://github.com/apaemre"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/apaemre/"

[[params.social]]
  name = "email"
  url = "mailto://apa.emre@metu.edu.tr"

